stages:
  split:
    cmd: python src/split.py data/data.xml
    deps:
    - data/data.xml
    - src/split.py
    outs:
    - data/splitted
  featurize:
    cmd: python src/featurization.py data/splitted data/features
    deps:
    - data/splitted
    - src/featurization.py
    params:
    - max_features
    - ngram_range.lo
    - ngram_range.hi
    outs:
    - data/features
  train:
    cmd: python src/train.py data/features model.pkl
    deps:
    - data/features
    - src/train.py
    outs:
    - model.pkl
  evaluate:
    cmd: python src/evaluate.py model.pkl data/features auc.json
    deps:
    - data/features
    - model.pkl
    - src/evaluate.py
    metrics:
    - auc.json:
        cache: false
