stages:
  prepare:
    cmd: uv run python src/dvc_example/prepare.py data/data.xml
    deps:
    - data/data.xml
    - src/dvc_example/prepare.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
  featurize:
    cmd: uv run python src/dvc_example/featurization.py data/prepared
      data/features
    deps:
    - data/prepared
    - src/dvc_example/featurization.py
    params:
    - featurize.max_features
    - featurize.ngrams
    outs:
    - data/features
  train:
    cmd: uv run python src/dvc_example/train.py data/features model.pkl
    deps:
    - data/features
    - src/dvc_example/train.py
    params:
    - train.min_split
    - train.n_est
    - train.seed
    outs:
    - model.pkl
