[project]
name = "dvc-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "veit", email = "veit@cusy.io" }
]
requires-python = ">=3.13"
dependencies = [
    "dvc",
]

[project.scripts]
dvc-example = "dvc_example:main"

[build-system]
requires = ["uv_build>=0.9.3,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit",
]
